// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNnNKoAx9HPuHOUrG9JUuEdzpHmrG9qkA',
    appId: '1:1005211420218:web:b059ddb319ba417dd2d703',
    messagingSenderId: '1005211420218',
    projectId: 'kiotchat-7006b',
    authDomain: 'kiotchat-7006b.firebaseapp.com',
    storageBucket: 'kiotchat-7006b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU2NfXGyyLu_bf0lyTK5GV22lOdG4U09g',
    appId: '1:1005211420218:android:6a16a9151c2f1cbdd2d703',
    messagingSenderId: '1005211420218',
    projectId: 'kiotchat-7006b',
    storageBucket: 'kiotchat-7006b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbmOvbbYEnhVlo3P4S-GhnshXgGFCycxs',
    appId: '1:1005211420218:ios:d7cf35cd18cbee9dd2d703',
    messagingSenderId: '1005211420218',
    projectId: 'kiotchat-7006b',
    storageBucket: 'kiotchat-7006b.appspot.com',
    iosBundleId: 'com.example.kb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbmOvbbYEnhVlo3P4S-GhnshXgGFCycxs',
    appId: '1:1005211420218:ios:d7cf35cd18cbee9dd2d703',
    messagingSenderId: '1005211420218',
    projectId: 'kiotchat-7006b',
    storageBucket: 'kiotchat-7006b.appspot.com',
    iosBundleId: 'com.example.kb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNnNKoAx9HPuHOUrG9JUuEdzpHmrG9qkA',
    appId: '1:1005211420218:web:86361ac63183804cd2d703',
    messagingSenderId: '1005211420218',
    projectId: 'kiotchat-7006b',
    authDomain: 'kiotchat-7006b.firebaseapp.com',
    storageBucket: 'kiotchat-7006b.appspot.com',
  );
}
